import React from 'react'

export const metadata = {
    title: "Planes Desarrollo Web",
    description: "Generated by Bird & Fang",
  };

const layout = ({ children }) => {
  return (
    <>
      {children}
    </>
  )
}

export default layout
