import Navbar from "@/components/Navbar";
import Hexagono from "@/components/Hexagono";
import HeaderHexagono from "@/app/hexagono/HeaderHexagono";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Informacion",
  description: "Generated by Bird & Fang",
};

const page = () => {
  return (
    <>
      <section className="mx-auto max-w-screen-xl">
        <Navbar />
        <HeaderHexagono />
        <Hexagono />
        <Footer />
      </section>
    </>
  );
};

export default page;
