import Navbar from "@/components/Navbar";
import Hexagono from "@/components/Hexagono";
import HeaderHexagono from "@/app/hexagono/HeaderHexagono";
import Footer from "@/components/Footer";
import Consultas from "@/components/Consultas";

export const metadata = {
  title: "Información",
  description: "Generated by Bird & Fang",
};

const page = () => {
  return (
    <>
      <section className="mx-auto max-w-screen-xl">
        <Navbar />
        <HeaderHexagono />
        <Hexagono />
        <Consultas />
        <Footer />
      </section>
    </>
  );
};

export default page;
